### ISSUE TITLE
Dependency conflict error

### ISSUE THREAD

**Issue by TugceOzberkYener** [fledge-iot/fledge-north-azure#18]
Hi, 

Recently when I was trying to use your plugin and install it on a machine which has Ubuntu OS, I come across to the below dependency conflict error.

![image](https://user-images.githubusercontent.com/54309809/220969801-4a86bd94-f6ec-49dd-a28c-90d35c88f8a6.png)

To solve this issue I had to clone the repo and manually add charset-normalizer==2.1.1 line inside the requirements-azure_iot.txt file and then pip3 install the dependencies.

With that change the problem has been solved and I am able to use the plugin now. It would be great if you can update the source code so that can still be used via apt install.

Kind regards,
Tugce

**Comment by ashish-jabble** [comment]
Hi @TugceOzberkYener yes there are conflicts of pip dependency, but does it complain to plugin discovery within Fledge or its working?
Also I see you have configured [latest](http://archives.fledge-iot.org/latest/ubuntu2004/x86_64/) archive repo package which is Fledge release **v2.1.0** and there is a bug with this plugin as we can't add it either as a north service or north task.
And now that problem has been resolved in develop branch. You may try our [nightly builds](http://archives.fledge-iot.org/nightly/ubuntu2004/x86_64/). 
fyi, we are just about to release next Fledge version `2.1.1` so packages will be available itself in latest archive repository.

**Comment by TugceOzberkYener** [comment]
Hi @ashish-jabble it looks like the north plugin is installed and can be used inside fledge but when I try to use the plug-in it does not send any data to iot hub and when i check the system logs i saw errors coming from the plugin - so it is not working without solving the dependency problem as of now

**Comment by ashish-jabble** [comment]
Hi @TugceOzberkYener requirements file updated via PR-https://github.com/fledge-iot/fledge-north-azure/pull/19 and will get merged soon into develop branch. Thanks!

**Comment by TugceOzberkYener** [comment]
Hi @ashish-jabble thanks for fixing the issue, now closing the issue
